name = "Custom Modpack 2"
author = "Fern"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bac70a1a4dd3ef6d1a0762f4482d9d59c5514c99d74f2d957ae38d36396d908"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
