name = "Custom Modpack 2"
author = "Fern"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac2baefb8b5abbebe3649f4176278e052db70efa6aa3fe269073a88f08b5c8fe"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
