name = "Custom Modpack 3"
author = "Fern"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a72bd3592dc1252ee9765bd82d2f1f9b4de44dcca09b7aa4ab6368fad804c90"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
